name: Run reproducer on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: aggregate without that dependency
      uses: gradle/gradle-build-action@v2
      with:
        arguments: testCodeCoverageReport -PremoveThatDependency
    - name: aggregate with the dependency
      uses: gradle/gradle-build-action@v2
      with:
        arguments: testCodeCoverageReport
